# Generated by Django 4.2.4 on 2023-08-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id_calculo', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.IntegerField()),
                ('altura', models.IntegerField()),
            ],
        ),
    ]
